source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import UserRegisterView, UserProfile, logout_view,  UserProfileEdit
from feed.views import PostCreateView, PostDetailedView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/sign_in.html'), name='log_in'),
    path('create/', UserRegisterView.as_view(), name='register_user'),
    path('profile/<int:profile_pk>', UserProfile.as_view(), name='profile'),
    path('profile/<int:profile_pk>/edit', UserProfileEdit.as_view(), name='edit_profile'),
    path('logout/', logout_view, name='log_out'),
    path('<int:profile_pk>/new_post/', PostCreateView.as_view(), name='new_post'),
    path('profile/<int:profile_pk>/post/<int:post_pk>/', PostDetailedView.as_view(), name='detailed_post')
]

source/lalavito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from feed.views import FeedView, PostDetailedView, SearchResultsView, ModerateView, PostDeleteView, PostEditView, CommentDeleteView
from accounts.views import UserRegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', FeedView.as_view(), name='feed'),
    path('sign_up/', UserRegisterView.as_view()),
    path('feed/<int:post_pk>/', PostDetailedView.as_view(), name='feed_post'),
    path('post_post/<int:post_pk>', PostEditView.as_view(), name='post_edit'),
    path('delete_post/', PostDeleteView.as_view(), name='delete_post'),
    path('delete_comment/', CommentDeleteView.as_view(), name='delete_comment'),
    path('search_result/', SearchResultsView.as_view(), name='search_results'),
    path('moderation/', ModerateView.as_view(), name='moderation')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(AbstractUser):
    name = models.CharField('Имя', max_length=100, blank=True, null=True)
    info = models.TextField('Инфо', max_length=1000, blank=True, null=True)
    number = models.IntegerField('Номер телефона', blank=True, null=True)

    def __str__(self):
        return self.username

source/accounts/forms.py
from accounts.models import Profile
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class NewUserForm(UserCreationForm):
    class Meta:
        model = Profile
        fields = [
            'username', 'password1', 'password2',
            'first_name',
            'info', 'number'
        ]
        widgets = {
            'username' : forms.TextInput(attrs={'placeholder': 'Логин', 'class': 'input_box'}),
            'first_name' : forms.TextInput(attrs={'placeholder': 'Имя', 'class': 'input_box'}),
            'info' : forms.Textarea(attrs={'placeholder': 'О себе', 'class': 'input_box text_box'}),
            'number' : forms.NumberInput(attrs={'placeholder': "Номер телефона (Без '+')", 'class': 'input_box'}),
        }
        
    def clean_email(self):
        email = self.cleaned_data['email']
        if len(email) < 1:
            raise forms.ValidationError("Email обязателен к заполнению!")
        return email
    
    def clean(self):
        cleaned_data = super().clean()
        if len(cleaned_data['first_name']) < 1:
            raise forms.ValidationError("Хотя бы одно поле ИМЕНИ должно быть заполнено")
        return cleaned_data
    

class UserEditForm(UserChangeForm):
    class Meta:
        model= Profile
        fields = [
            'first_name', 'email', 
            'info', 'number'
        ]
        widgets = {
            'first_name' : forms.TextInput(attrs={'placeholder': 'Имя', 'class': 'input_box'}),
            'email' : forms.EmailInput(attrs={'placeholder': 'Электронная почта', 'class': 'input_box'}),
            'info' : forms.Textarea(attrs={'placeholder': 'О себе', 'class': 'input_box text_box'}),
            'number' : forms.NumberInput(attrs={'placeholder': 'Номер телефона', 'class': 'input_box'}),
        }

        

source/accounts/views.py
from django.contrib.auth import login, logout
from django.views.generic import CreateView, DetailView, UpdateView
from accounts.models import Profile
from accounts.forms import NewUserForm, UserEditForm
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

def logout_view(request):
    logout(request)
    return redirect('feed')

class UserRegisterView(CreateView):
    model = Profile
    template_name = 'accounts/sign_up.html'
    form_class = NewUserForm

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(reverse('feed'))
    
    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('feed')
        return next_url
    
class UserProfile(DetailView):
    template_name = 'accounts/profile_page.html'
    model = Profile
    context_object_name = 'profile_obj'
    pk_url_kwarg = 'profile_pk'


class UserProfileEdit(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:log_in'
    model = Profile
    form_class = UserEditForm
    template_name = 'accounts/edit_profile.html'
    pk_url_kwarg = 'profile_pk'
    context_object_name = 'profile_obj'

    def get_success_url(self, **kwargs):
        return reverse('accounts:profile', kwargs={'profile_pk': self.request.user.pk})
    
    def get_context_data(self, **kwargs):
        kwargs['profile_obj'] = self.get_object()
        kwargs['form'] = self.get_form()
        return super().get_context_data(**kwargs)
    

source/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}    
    <div class="card card_form mt-5">
        <img src="{{profile_obj.avatar.url}}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Редактирование профиля</h5>  
            <div class="form-control mb-3 mt-3">{{form.info}}</div>
            <div class="form-control mb-3 mt-3">{{form.number}}</div>
            <button type="submit" class="btn btn-primary">Подтвердить</button>
        </div>
      </div>
</form>
{% endblock %}

source/templates/accounts/profile_page.html
{% extends "base.html" %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block title %}Main Page{% endblock %}
{% block content %}
        <div class="container mt-5">
            <div class="usr_info d-flex flex-row justify-content-around" style="width: 50%;">
                <div class="usr_avatar" style="width: 20%;">
                    <img class="user_avatar" src="{{profile_obj.avatar.url}}" style="width: 100%;" alt="">
                </div>
                <div class="text_info">
                    <div class="usr_name">
                        <div class="d-flex flex-row">
                            <h3>{{profile_obj.username}}</h3>
                            {% if request.user == profile_obj %}
                                <a href="{% url 'accounts:edit_profile' profile_obj.pk %}" class="btn btn-secondary ms-5">Редактирование</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="counts mt-3">
                        <span>{{profile_obj.usr_posts.all.count}} Публикаций</span>
                    </div>
                    <div class="usr_bio mt-3">
                        <h6>{{profile_obj.first_name}}</h6>
                        <p>{{profile_obj.info}}</p>
                        <p>{{profile_obj.number}}</p>
                    </div>
                </div>
            </div>
            <div class="posts d-flex flex-row mt-3">
                {% if request.user != profile_obj %}
                    {% for post in profile_obj.usr_posts.all %}
                        {% if post.moderate == 'M' %}
                            <div class="card m-3 justify-content-center" style="width: 18rem;">
                                <a href="{% url 'accounts:detailed_post' profile_obj.pk post.pk %}"><img src="{{post.image.url}}" class="img-fluid"></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    {% for post in profile_obj.usr_posts.all %}
                        {% if post.moderate != 'D' %}
                            <div class="card m-3 justify-content-center" style="width: 18rem;">
                                <a href="{% url 'accounts:detailed_post' user.pk post.pk %}"><img src="{{post.image.url}}" class="img-fluid"></a>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <style>
            .img-fluid {
                display: block;
                margin: auto;
            }
        </style>
    
{% endblock %}

source/templates/accounts/sign_in.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post">
{% csrf_token %}    
    <div class="card card_form mt-5">
        <img src="{% static 'images/title.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Вход</h5> 
            <div class="form-control mt-3">{{form.username}} <span>Логин</span></div>
            <div class="form-control mt-3">{{form.password}} <span>Паролль</span></div>
            <button type="submit" class="btn btn-primary mt-3">Войти</button>
            <a href="{% url 'accounts:register_user' %}" type="submit" class="btn btn-primary mt-3">Регистрация</a> 
        </div>
      </div>
</form>
{% endblock %}

source/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
{% csrf_token %}    
    <div class="card card_form mt-5">
        <img src="{% static 'images/title2.png' %}" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Регистрация</h5>  
            <div class="form-control mb-3 mt-3">{{form.username}}</div>
            <h6>Придумайте пароль</h6>
            <div class="form-control mb-3 mt-3">{{form.password1}}</div>
            <h6>Подтвердите пароль</h6>
            <div class="form-control mb-3 mt-3">{{form.password2}}</div>
            <div class="form-control mb-3 mt-3">{{form.first_name}}</div>
            <div class="form-control mb-3 mt-3">{{form.info}}</div>
            <div class="form-control mb-3 mt-3">{{form.number}}</div>
            <button type="submit" class="btn btn-primary">Подтвердить</button>
        </div>
      </div>
</form>
{% endblock %}