source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import UserRegisterView, UserProfile, logout_view,  UserProfileEdit
from feed.views import PostCreateView, PostDetailedView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/sign_in.html'), name='log_in'),
    path('create/', UserRegisterView.as_view(), name='register_user'),
    path('profile/<int:profile_pk>', UserProfile.as_view(), name='profile'),
    path('profile/<int:profile_pk>/edit', UserProfileEdit.as_view(), name='edit_profile'),
    path('logout/', logout_view, name='log_out'),
    path('<int:profile_pk>/new_post/', PostCreateView.as_view(), name='new_post'),
    path('profile/<int:profile_pk>/post/<int:post_pk>/', PostDetailedView.as_view(), name='detailed_post')
]

source/lalavito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from feed.views import FeedView, PostDetailedView, SearchResultsView, ModerateView, PostDeleteView, PostEditView, CommentDeleteView
from accounts.views import UserRegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', FeedView.as_view(), name='feed'),
    path('sign_up/', UserRegisterView.as_view()),
    path('feed/<int:post_pk>/', PostDetailedView.as_view(), name='feed_post'),
    path('post_post/<int:post_pk>', PostEditView.as_view(), name='post_edit'),
    path('delete_post/', PostDeleteView.as_view(), name='delete_post'),
    path('delete_comment/', CommentDeleteView.as_view(), name='delete_comment'),
    path('search_result/', SearchResultsView.as_view(), name='search_results'),
    path('moderation/', ModerateView.as_view(), name='moderation')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/feed/models.py
from django.db import models

from accounts.models import Profile

class Category(models.Model):
    title = models.CharField('Название', max_length=150)

    def __str__(self):
        return f'{self.title}'


class PostModel(models.Model):
    MOD_CHOICES = (
        ('M', 'Опубликовано'),
        ('W', 'На модерации'),
        ('U', 'Отклонено'),
        ('D', 'На удаление')
    )

    image = models.ImageField('Картинка', upload_to='post_images', null=True, blank=True)
    author = models.ForeignKey(Profile, verbose_name='Пользователь', related_name='usr_posts', on_delete=models.CASCADE)
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст публикации', max_length=1000)
    category = models.ForeignKey(Category, verbose_name='Категория', related_name='pCategory', on_delete=models.SET_NULL, null=True, blank=True)
    price = models.IntegerField('Цена', default=1)
    moderate = models.CharField('Модерация', max_length=1, blank=False, null=True, choices=MOD_CHOICES, default='W')
    date_add = models.DateTimeField('Дата публикации', auto_now_add=True)
    date_edit = models.DateTimeField('Дата редактирования', auto_now=True)
    date_moderate = models.DateTimeField('Дата публикации', null=True, blank=True)

    class Meta:
        permissions = (
            ("moderate", "Можем модерировать объявление"),
        )
    

class CommentModel(models.Model):
    class Meta:
        ordering = ['date_add']

    author = models.ForeignKey(Profile, verbose_name='Пользователь', related_name='a_comment', on_delete=models.SET_NULL, blank=True, null=True)
    post_model = models.ForeignKey(PostModel, verbose_name='Продукт', related_name='p_comment', on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField('Текст комментария', max_length=1500)
    date_add = models.DateField('Дата публикации', auto_now_add=True)
    date_edit = models.DateField('Дата редактирования', auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_author(self):
        return Profile.objects.get(username=self.author)
    
    def get_product(self):
        return PostModel.objects.get(id=self.post_model)

source/feed/forms.py
from django.forms import ModelForm, Textarea
from feed.models import PostModel, CommentModel
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = PostModel
        fields = [
            'image',
            'title',
            'text',
            'category',
            'price'
        ]
        widgets = {
            'text' : forms.Textarea(attrs={'placeholder': 'Описание', 'class': 'input_box text_box'}),
            'title' : forms.TextInput(attrs={'placeholder': 'Название', 'class': 'input_box text_box'}),
            'price' : forms.NumberInput(attrs={'placeholder': 'Цена', 'class': 'input_box text_box'}),
        }

class CommentForm(ModelForm):
    class Meta:
        model = CommentModel
        fields = [
            'text'
        ]
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Оставьте комментарий',
                'style': "height: 150px"
            })
        }

source/feed/views.py
from typing import Any
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from feed.forms import CommentForm, PostForm
from feed.models import PostModel, CommentModel
from datetime import datetime
from django.views.generic.edit import FormMixin
from django.db.models import Q
from django.http import JsonResponse

class SearchResultsView(ListView):
    model = PostModel
    template_name = "search_results.html"
    ordering = ['-date_add']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['this_objects'] = self.get_queryset()
        print(context['this_objects'])
        return context
    
    def get_queryset(self):
        query = self.request.GET.get("q")
        this_objects = PostModel.objects.filter(
            Q(title__icontains=query) | 
            Q(text__icontains=query)
        )
        return this_objects
    

class FeedView(ListView):
    template_name = 'feed.html'
    context_object_name = 'post_obj'
    model = PostModel

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context =  super().get_context_data(**kwargs)
        context['post_obj'] = PostModel.objects.all().order_by('date_add')
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = 'accounts:log_in'
    template_name = 'content/new_post.html'
    form_class = PostForm
    model = PostModel

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        print(kwargs)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_invalid(self, form):
        print(form.data)
        print(form.errors)
        print(self.request.POST.dict())
        return redirect('feed')
    
    def form_valid(self, form):
        print(self.request.user)
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return redirect('feed')
 

class PostDetailedView(FormMixin, DetailView):
    login_url = 'accounts:log_in'
    template_name = 'detailed_post.html'
    model = PostModel
    form_class = CommentForm
    context_object_name = 'post'
    pk_url_kwarg = 'post_pk'

    def get_success_url(self, **kwargs) -> str:
        return reverse_lazy('feed')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.post_model = self.get_object()
        self.object.save()
        return super().form_valid(form)
    

class ModerateView(ListView):
    template_name='moderate.html'
    context_object_name = 'post_obj'
    model = PostModel

    def post(self, request, *args, **kwargs):
        mod = request.POST.get('mod')
        post = PostModel.objects.get(id=request.POST.get('postid'))
        answer = {}
        if mod == 'yes':
            post.moderate = 'M'
            post.date_moderate = datetime.now()
            answer['answer'] = 'Опубликовано'

        elif mod == 'no':
            post.moderate = 'U'
            answer['answer'] = 'Отклонено'

        post.save()
        return JsonResponse(answer)


class PostEditView(LoginRequiredMixin, UpdateView):
    login_url = 'accounts:log_in'
    model = PostModel
    form_class = PostForm
    template_name = 'content/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post_obj'

    def get_success_url(self, **kwargs):
        return reverse('feed')
    
    def get_context_data(self, **kwargs):
        kwargs['post_obj'] = self.get_object()
        kwargs['form'] = self.get_form()
        return super().get_context_data(**kwargs)


class PostDeleteView(View):
    def post(self, request, *args, **kwargs):
        post = PostModel.objects.get(id=request.POST.get('postid'))
        answer = {}
        post.moderate = 'D'
        post.date_moderate = datetime.now()
        answer['answer'] = 'На удаление'
        post.save()
        return JsonResponse(answer)
    
class CommentDeleteView(View):
    def post(self, request, *args, **kwargs):
        comment = CommentModel.objects.get(id=request.POST.get('commentid'))
        comment.delete()
        answer = {}
        answer['answer'] = 'Комментарий удален'
        return JsonResponse(answer)






    

source/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>
<body style="background-color:rgb(230, 229, 227) !important;">
    <nav class="navbar navbar-expand-lg bg-body-tertiary row justify-content-around">

            <div class="col-3 d-flex flex-row">
                <div class="col-6 text-center">
                    <a href="{% url 'feed' %}" class="link-dark">
                        <img class="img-fluid" src="{% static 'images/title.png' %}" alt="" width="180px">
                    </a>
                </div>
            </div>
            
            <div class="col-4">
                <form action="{% url 'search_results' %}" method="get">
                    <input name="q" class="input_box" type="text" placeholder="Поиск" style="width: 70%; border: 2px solid rgb(230, 229, 227);border-radius:5px">
                </form>
            </div>
            
                <div class="col-4 text-center">
                    
                    {% if user.is_authenticated %}
                        {% if perms.feed.moderate %}
                            <a href="{% url 'moderation' %}" class="btn btn-secondary">Модерация</a>
                        {% endif %}
                        <a href="{% url 'accounts:log_out' %}" class="btn btn-danger">Выход</a>
                        <a href="{% url 'accounts:new_post' user.pk %}" class="btn btn-success">Публикация</a>
                        <a href="{% url 'accounts:profile' user.pk %}" class="link-dark">
                            <i class="bi bi-person dark fs-1"></i>
                        </a>
                    {% else %}
                        <a href="{% url 'accounts:log_in' %}" class="btn btn-primary">Войти</a>
                    {% endif %}
                </div>
            

    </nav>
    <div class="container">
        <div class="background"></div>
        {% block content %}{% endblock %}
    </div>
    <script>
        $(document).on('click', '#delete', function(e) {
            const val = $(this).val()
            const an = $(this).attr('id')
            const b = this
            e.preventDefault()
            $.ajax({
                headers: {"X-CSRFToken": '{{csrf_token}}'},
                type: 'POST',
                url: "{% url 'delete_post' %}",
                data: {
                    postid: $(this).val(),
                    mod: $(this).attr('id'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(json) {
                    console.log(json)
                    let c = `"${val}"`
                    let status = document.querySelector(`[data-artId=${c}]`)
                    status.innerHTML = json['answer']
                }
            })
        })
    </script>
</body>
</html>

source/templates/detailed_post.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% include 'partial/posts_form.html' %}
    {% if request.user != post.author %}
      
        <form method="post">
            {% csrf_token %}
            <div class="row comments">
              <h6 id="write_comment">Написать комментарий</h6>
                <div class="col-12">
                    {{form.text}}
                </div>
              <button type="submit" class="btn btn-primary mt-3 mb-3">Комментировать</button>
            </div>
            
        </form>
      {% endif %}
      {% for comment in post.p_comment.all %}
        <div class="card comments" data-artId="{{comment.pk}}">
          <div class="card-body">
            <span class="card-title fs-4 fw-medium">
                <a href="{% url 'accounts:profile' comment.get_author.pk %}" class="text-dark" style="text-decoration: none;">{{comment.get_author}}</a>
            </span>
            <p class="card-text">{{comment.text}}</p>
            {% if request.user == comment.author %}
              <button id='delete_comment' class="btn btn-danger" value="{{comment.pk}}">Удалить</button>
            {% endif %}
          </div>
            
        </div>
      {% endfor %}
    </div>  
  </div>
</div>
<script>
  $(document).on('click', '#delete_comment', function(e) {
      const val = $(this).val()
      const an = $(this).attr('id')
      e.preventDefault()
      $.ajax({
          headers: {"X-CSRFToken": '{{csrf_token}}'},
          type: 'POST',
          url: "{% url 'delete_comment' %}",
          data: {
              commentid: $(this).val(),
              csrfmiddlewaretoken: '{{ csrf_token }}',
              action: 'post'
          },
          success: function(json) {
              console.log(json)
              let c = `"${val}"`
              let comment = document.querySelector(`[data-artId=${c}]`)

              comment.remove()
          }
      })
  })
</script>
{% endblock %}

source/templates/feed.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% for post in post_obj %}
        {% if post.moderate == 'M' %}
            {% include 'partial/posts_form.html' %}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

source/templates/moderate.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% for post in post_obj %}
        {% if post.moderate == 'W' %}
            {% include 'partial/posts_form.html' %}
            <div>
                <button id='yes' class="btn btn-success" value="{{post.pk}}">Опубликовать</button>
                <button id='no' class="btn btn-danger" value="{{post.pk}}">Отклонить</button>
            </div>
        {% endif %}
    {% endfor %}
    <script>
        $(document).on('click', '.btn', function(e) {
            const val = $(this).val()
            const an = $(this).attr('id')
            const b = this
            e.preventDefault()
            $.ajax({
                headers: {"X-CSRFToken": '{{csrf_token}}'},
                type: 'POST',
                url: "{% url 'moderation' %}",
                data: {
                    postid: $(this).val(),
                    mod: $(this).attr('id'),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post'
                },
                success: function(json) {
                    console.log(json)
                    let c = `"${val}"`
                    let status = document.querySelector(`[data-artId=${c}]`)
                    status.innerHTML = json['answer']
                }
            })
        })
    </script>
</div>
{% endblock %}

source/templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block style %}{% static 'css/style.css' %}{% endblock %}
{% block content %}
<div class="user_feed">
    {% for post in this_objects %}
        {% if post.moderate == 'M' %}
            {% include 'partial/posts_form.html' %}
        {% endif %}
    {% endfor %}
</div>
{% endblock %}