source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import UserRegisterView, UserProfile, logout_view,  UserProfileEdit
from feed.views import PostCreateView, PostDetailedView

app_name='accounts'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='accounts/sign_in.html'), name='log_in'),
    path('create/', UserRegisterView.as_view(), name='register_user'),
    path('profile/<int:profile_pk>', UserProfile.as_view(), name='profile'),
    path('profile/<int:profile_pk>/edit', UserProfileEdit.as_view(), name='edit_profile'),
    path('logout/', logout_view, name='log_out'),
    path('<int:profile_pk>/new_post/', PostCreateView.as_view(), name='new_post'),
    path('profile/<int:profile_pk>/post/<int:post_pk>/', PostDetailedView.as_view(), name='detailed_post')
]

source/lalavito/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from feed.views import FeedView, PostDetailedView, SearchResultsView, ModerateView, PostDeleteView, PostEditView, CommentDeleteView
from accounts.views import UserRegisterView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', FeedView.as_view(), name='feed'),
    path('sign_up/', UserRegisterView.as_view()),
    path('feed/<int:post_pk>/', PostDetailedView.as_view(), name='feed_post'),
    path('post_post/<int:post_pk>', PostEditView.as_view(), name='post_edit'),
    path('delete_post/', PostDeleteView.as_view(), name='delete_post'),
    path('delete_comment/', CommentDeleteView.as_view(), name='delete_comment'),
    path('search_result/', SearchResultsView.as_view(), name='search_results'),
    path('moderation/', ModerateView.as_view(), name='moderation')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/feed/models.py
from django.db import models

from accounts.models import Profile

class Category(models.Model):
    title = models.CharField('Название', max_length=150)

    def __str__(self):
        return f'{self.title}'


class PostModel(models.Model):
    MOD_CHOICES = (
        ('M', 'Опубликовано'),
        ('W', 'На модерации'),
        ('U', 'Отклонено'),
        ('D', 'На удаление')
    )

    image = models.ImageField('Картинка', upload_to='post_images', null=True, blank=True)
    author = models.ForeignKey(Profile, verbose_name='Пользователь', related_name='usr_posts', on_delete=models.CASCADE)
    title = models.CharField('Заголовок', max_length=100)
    text = models.TextField('Текст публикации', max_length=1000)
    category = models.ForeignKey(Category, verbose_name='Категория', related_name='pCategory', on_delete=models.SET_NULL, null=True, blank=True)
    price = models.IntegerField('Цена', default=1)
    moderate = models.CharField('Модерация', max_length=1, blank=False, null=True, choices=MOD_CHOICES, default='W')
    date_add = models.DateTimeField('Дата публикации', auto_now_add=True)
    date_edit = models.DateTimeField('Дата редактирования', auto_now=True)
    date_moderate = models.DateTimeField('Дата публикации', null=True, blank=True)

    class Meta:
        permissions = (
            ("moderate", "Можем модерировать объявление"),
        )
    

class CommentModel(models.Model):
    class Meta:
        ordering = ['date_add']

    author = models.ForeignKey(Profile, verbose_name='Пользователь', related_name='a_comment', on_delete=models.SET_NULL, blank=True, null=True)
    post_model = models.ForeignKey(PostModel, verbose_name='Продукт', related_name='p_comment', on_delete=models.CASCADE, blank=True, null=True)
    text = models.TextField('Текст комментария', max_length=1500)
    date_add = models.DateField('Дата публикации', auto_now_add=True)
    date_edit = models.DateField('Дата редактирования', auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def get_author(self):
        return Profile.objects.get(username=self.author)
    
    def get_product(self):
        return PostModel.objects.get(id=self.post_model)

source/templates/partial/posts_form.html
  <div class="card mt-3 mb-3" style="width: 70%; margin: auto">
    <div class="card-body row">
      <div class="col-12">
        <a href="{% url 'accounts:profile' post.author.pk %}" class="text-dark" style="text-decoration: none;"><h5 class="card-title">{{post.author}}</h5></a>
        <h6>{{post.author.number}}</h6>
        {% if request.user == post.author %}
          <button id='delete' class="btn btn-danger" value="{{post.pk}}">Удалить</button>
          {% if post.moderate != 'U' %}
            <a href="{% url 'post_edit' post.pk %}" class="btn btn-primary" value="{{post.pk}}">Редактировать</a>
          {% endif %}
        {% endif %}
      </div>
    </div>
    <a href="{% url 'feed_post' post.pk %}" class="card-img-top">
      <div class="justify-content-center d-flex">
        <img src="{{post.image.url}}" >
      </div>
    </a>

    <div class="card-body">
      <p class="card-text">{{post.text}}</p>
      <h6 class="card-text" data-artId="{{post.pk}}">{{post.get_moderate_display}}</h6>
      <div class="sub_section d-flex flex-row">
        <div class="col-4">
          <span>Категория:</span>
          <h6 id="sub" >{{post.category}}</h6>
        </div>
        <div class="col-4">
          <span>Цена:</span>
          <h6 id="sub">{{post.price}}</h6>
        </div>
        <div class="col-4">
          <span>Дата публикации</span>
          <h6 id="" >
            {% if post.moderation != 'M' %}
              {{post.date_add}}
            {% else %}
              {{post.date_moderate}}
            {% endif %}
            </h6>
        </div>
      </div>
    </div>
  </div>

    
      